#active: dev/test/prod
spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: spring-boot-restful-api
  datasource:
    driver-class-name: @database.driver.name@
    url: @database.url@
    username: @database.username@
    password: @database.password@
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    #Open Session In View
    open-in-view: false
    # 指定schema(default_catalog)
    properties:
      hibernate:
        default_schema: @database.schema@
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: @server.port@

#配置logback變數
logback:
  path: @logback.path@
  name: @logback.name@